import { tsConfig, jsConfig, rollupConfig, testingConfig } from '@joint/eslint-config';
import { defineConfig } from 'eslint/config';

export default defineConfig([
    ...jsConfig,
    ...tsConfig,
    ...rollupConfig,
    ...testingConfig,
    {
        // Autogenerated files
        ignores: ['coverage/'],
    },
    {
        // Tests
        files: ['**/test/**'],
        languageOptions: {
            globals: {
                joint: 'readonly',
                graphlib: 'readonly',
                QUnit: 'readonly',
                should: 'readonly',
            },
        }
    },
]);
