import { tsConfig, jsConfig } from '@joint/eslint-config';
import { defineConfig } from 'eslint/config';

export default defineConfig([
    ...jsConfig,
    ...tsConfig,
    {
        // Autogenerated folder
        ignores: ['mocks/dist/'],
    },
]);
