module.exports = {
    'shapes.erd':
        ['plugins/shapes/joint.shapes.erd.js'],
    'shapes.fsa':
        ['plugins/shapes/joint.shapes.fsa.js'],
    'shapes.org':
        ['plugins/shapes/joint.shapes.org.js'],
    'shapes.chess':
        ['plugins/shapes/joint.shapes.chess.js'],
    'shapes.pn':
        ['plugins/shapes/joint.shapes.pn.js'],
    'shapes.devs':
        ['plugins/shapes/joint.shapes.devs.js'],
    'shapes.uml':
        ['plugins/shapes/joint.shapes.uml.js'],
    'shapes.logic':
        ['plugins/shapes/joint.shapes.logic.js'],
    'layout.DirectedGraph':
        ['plugins/layout/DirectedGraph/joint.layout.DirectedGraph.js']
};
