language: node_js
dist: focal
node_js:
  - 18
addons:
  apt:
    packages:
      # Thai
      - language-pack-th
      # Amharic
      - language-pack-am
      # Arabic
      - language-pack-ar
      # Lithuanian
      - language-pack-lt
      # Azerbaijani
      - language-pack-az
      # Slovenian
      - language-pack-sl
      # Icelandic
      - language-pack-is
      # Vietnamese
      - language-pack-vi
      # Turkish
      - language-pack-tr
      # Romanian
      - language-pack-ro
      # Japanese
      - language-pack-ja
      - japan*
      # Chinese
      - language-pack-zh*
      - chinese*
      # Korean
      - language-pack-ko
      - korean*
      # Fonts
      - fonts-arphic-ukai
      - fonts-arphic-uming
      - fonts-ipafont-mincho
      - fonts-ipafont-gothic
      - fonts-unfonts-core

before_install:
  - npm install -g grunt-cli

install: npm install

before_script:
  - grunt install

script:
  - npm run test
  - npm run lint
