language: node_js
node_js:
  - 16

before_install:
  - npm install -g grunt-cli

install:
  - npm install --workspaces

before_script:
  - npm run grunt:install --workspaces --if-present

script:
  - npm run test --workspaces --if-present
  - npm run lint --workspaces --if-present
