language: node_js
node_js:
  - 16

before_install:
  - yarn global add grunt-cli
  - corepack enable

install:
  - yarn install

before_script:
  - yarn run build

script:
  - yarn run test
  - yarn run lint
