language: node_js
dist: focal
node_js:
  - 18
addons:
  apt:
    packages:
      # Fonts - util.breakText - international characters
      - fonts-arphic-ukai
      - fonts-arphic-uming
      - fonts-ipafont-mincho
      - fonts-ipafont-gothic
      - fonts-unfonts-core
      - fonts-noto-core

before_install:
  - npm install -g grunt-cli
  - corepack enable

install:
  - yarn install

before_script:
  - yarn run dist

script:
  - yarn run test
  - yarn run lint
