language: node_js
dist: focal
node_js:
  - 18
addons:
  apt:
    packages:
      # Fonts - util.breakText - international characters
      - fonts-arphic-ukai
      - fonts-arphic-uming
      - fonts-ipafont-mincho
      - fonts-ipafont-gothic
      - fonts-unfonts-core
      - fonts-noto-core

before_install:
  - npm install -g grunt-cli

install: npm install

before_script:
  - grunt install

script:
  - npm run test
  - npm run lint
