compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - level: discard
    text: "load-grunt-config@npm:0.19.2 doesn't provide grunt (p9ff33), requested by jit-grunt"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.7.0.cjs
