name: Bug Report
description: Something doesn't work like it should? Provide the steps for us to reproduce the bug!
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        This form is for bug reports only, and it's required that you provide the steps to reproduce the bug. If you are unsure if the issue is a bug, or if you need to ask a general question, create a GitHub [discussion](https://github.com/clientIO/joint/discussions) instead.
  - type: textarea
    id: current-versus-expected-behaviour
    attributes:
      label: Current versus expected behaviour
      description: What happened, and did you expect to happen? If relevant, add code examples, screenshots, etc.
      placeholder: |
        Describe the bug, and what the expected behaviour should be.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide the steps to reproduce the bug.
      placeholder: |
        1. Open the ...
        2. Click on an element ...
        3. The behaviour should be ...
        4. Under these conditions what actually happens is ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our library are you running?
      placeholder: X.Y.Z
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Safari on iOS
        - Android (State browser in description)
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Mac
        - Linux
