name: Bug Report
description: Something doesn't work like it should? Tell us!
title: "[Bug]: "
labels: ["bug"]
assignees: 
  - ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! If you need to ask a general question, create a github [discussion](https://github.com/clientIO/joint/discussions).
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? If relevant, add code examples, screenshots, steps to reproduce, etc.
      placeholder: Describe the bug!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our library are you running?
      placeholder: X.Y.Z
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Safari on iOS
        - Android (State browser in description)
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Mac
        - Linux
