blank_issues_enabled: false
contact_links:
  - name: Join our GitHub Discussions community
    url: https://github.com/clientIO/joint/discussions
    about: Ask and discuss questions with other community members
