import { tsConfig, jsConfig, rollupConfig } from '@joint/eslint-config';
import { defineConfig } from 'eslint/config';

export default defineConfig([
    ...jsConfig,
    ...tsConfig,
    ...rollupConfig,
    {
        // Autogenerated files
        ignores: ['coverage/'],
    },
    {
        // Tests
        files: ['**/test/**'],
        languageOptions: {
            globals: {
                joint: 'readonly',
                QUnit: 'readonly',
            },
        },
    },
]);
