import js from '@eslint/js';
import { defineConfig } from 'eslint/config';
import globals from 'globals';

/**
 * Common ESLint rules shared between JavaScript and TypeScript files
 * @type {import('eslint').Linter.RulesRecord}
 */
export const commonRules = {
    // ESLint Core Rules
    // Enforce 4-space indentation with special handling for switch cases
    indent: ['error', 4, { SwitchCase: 1 }],
    // Disallow console.log but allow console.warn for debugging
    'no-console': ['error', { allow: ['warn'] }],
    // Allow constant conditions (useful for while(true) loops)
    'no-constant-condition': ['off'],
    // Allow direct prototype builtin access
    'no-prototype-builtins': ['off'],
    // Enforce spaces inside object curly braces, but not between braces
    'object-curly-spacing': ['error', 'always', { objectsInObjects: false }],
    // Enforce single quotes for strings
    quotes: ['error', 'single'],
    // Require semicolons at the end of statements
    semi: ['error', 'always'],
    // Disallow space before function parentheses
    'space-before-function-paren': ['error', 'never'],
    // Enforce const for variables that are never reassigned
    'prefer-const': ['error'],
    // Allow var declarations (legacy code support)
    'no-var': ['off'],
};

/**
 * ESLint config to support all JavaScript files with .js, .jsx, .mjs extensions
 */
export const jsConfig = defineConfig([
    {
        // Autogenerated folders
        ignores: ['build/', 'dist/', 'node_modules/'],
    },
    {
        // Common globals for all checked files
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
            },
        },
    },
    {
        // JavaScript base config - applies to all .js, .jsx, .mjs files
        files: ['**/*.js', '**/*.jsx', '**/*.mjs'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
        },
        extends: [js.configs.recommended],
        rules: {
            // Apply common rules
            ...commonRules,

            // Report unused variables (local scope only, ignore function arguments)
            'no-unused-vars': ['error', { vars: 'local', args: 'none' }],
        },
    },
]);
