import { jsConfig, tsConfig, testingConfig } from '@joint/eslint-config';
import { defineConfig } from 'eslint/config';

export default defineConfig([
    ...jsConfig,
    ...tsConfig,
    ...testingConfig,
    {
        // Autogenerated files
        ignores: ['coverage/', '**/test/ts/*.js*'],
    },
    {
        // Typescript definition files
        files: ['**/*.d.ts'],
        rules: {
            // `@typescript-eslint` plugin is defined in `tsConfig`
            '@typescript-eslint/no-explicit-any': ['off'],
        },
    },
    {
        // Tests
        files: ['**/test/**'],
        languageOptions: {
            globals: {
                joint: 'readonly',
                V: 'readonly',
                g: 'readonly',
                $: 'readonly',
                _: 'readonly',
                QUnit: 'readonly',
                sinon: 'readonly',
                simulate: 'readonly',
                fixtures: 'readonly',
            },
        },
    },
    {
        // Demos
        files: ['**/demo/**'],
        languageOptions: {
            globals: {
                joint: 'readonly',
                V: 'readonly',
                g: 'readonly',
            },
        },
        rules: {
            'no-console': 'off',
            'no-redeclare': 'off',
            'no-unused-vars': 'off',
            'no-var': 'off',

            // `@typescript-eslint` plugin is defined in `tsConfig`
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-namespace': 'off',
        },
    },
]);
