name: Publish Joint React Docs

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - feat/release-joint-react-storybook
  workflow_call:

jobs:
  build-joint-react-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/joint-react

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22.14.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
          key: yarn-cache-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies from root
        run: yarn install --immutable
        working-directory: ./

      - name: Ensure docs folders
        run: |
          mkdir -p docs/joint-react-storybook
          mkdir -p docs/joint-react-api

      - name: Build Storybook
        run: NODE_ENV=production yarn build-storybook -o docs/joint-react-storybook

      - name: Build Typedoc
        run: NODE_ENV=production yarn docs:typedoc

      - name: Upload built docs
        uses: actions/upload-artifact@v4
        with:
          name: joint-react-docs
          path: packages/joint-react/docs

  deploy-docs:
    needs: build-joint-react-docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download built docs
        uses: actions/download-artifact@v4
        with:
          name: joint-react-docs
          path: ./packages/joint-react/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/joint-react/docs
