name: Publish Joint React Docs

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - feat/release-joint-react-storybook
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-joint-react-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/joint-react

    outputs:
      pages_path: ${{ steps.prepare.outputs.pages_path }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.14.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
          key: yarn-cache-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies from root
        run: yarn install --immutable
        working-directory: ./

      - name: Build @joint/core package
        run: yarn workspace @joint/core build
        working-directory: ./

      - name: Ensure docs folders
        id: prepare
        run: |
          mkdir -p docs/joint-react-storybook
          mkdir -p docs/joint-react-api
          echo "pages_path=$(pwd)/docs" >> $GITHUB_OUTPUT

      - name: Build Storybook
        env:
          STORYBOOK_BASE_DOCS_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/joint-react-api
        run: |
          echo "Using BASE_DOCS_URL=$STORYBOOK_BASE_DOCS_URL"
          yarn build-storybook -o docs/joint-react-storybook


      - name: Build Typedoc
        run: NODE_ENV=production yarn docs:typedoc

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/joint-react/docs

  deploy-docs:
    needs: build-joint-react-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
